### ISSUE TITLE
Build Fails under Qt 5.11

### ISSUE THREAD

**Issue by meanjollies** [Jmgr/actiona#78]
Hello,

After upgrading Qt from 5.10 to 5.11, the make process fails:

```
[...]
coloredit.cpp: In constructor ‘ActionTools::ColorEdit::ColorEdit(QWidget*)’:
coloredit.cpp:38:132: error: invalid use of incomplete type ‘class QRegExpValidator’
         mValidator(new QRegExpValidator(QRegExp("^\\d\\d{0,2}:\\d\\d{0,2}:\\d\\d{0,2}$", Qt::CaseSensitive, QRegExp::RegExp2), this))
                                                                                                                                    ^
In file included from coloredit.cpp:21:
coloredit.h:36:7: note: forward declaration of ‘class QRegExpValidator’
 class QRegExpValidator;
       ^~~~~~~~~~~~~~~~
coloredit.cpp:42:51: error: no matching function for call to ‘ActionTools::CodeLineEdit::setValidator(QRegExpValidator*&)’
         ui->colorLineEdit->setValidator(mValidator);
                                                   ^
In file included from /usr/include/qt/QtWidgets/QLineEdit:1,
                 from ./codelineedit.h:28,
                 from generated/ui_coloredit.h:19,
                 from coloredit.cpp:22:
/usr/include/qt/QtWidgets/qlineedit.h:122:10: note: candidate: ‘void QLineEdit::setValidator(const QValidator*)’
     void setValidator(const QValidator *);
          ^~~~~~~~~~~~
/usr/include/qt/QtWidgets/qlineedit.h:122:10: note:   no known conversion for argument 1 from ‘QRegExpValidator*’ to ‘const QValidator*’
coloredit.cpp: In member function ‘void ActionTools::ColorEdit::on_colorLineEdit_codeChanged(bool)’:
coloredit.cpp:164:55: error: no matching function for call to ‘ActionTools::CodeLineEdit::setValidator(QRegExpValidator*&)’
             ui->colorLineEdit->setValidator(mValidator);
                                                       ^
In file included from /usr/include/qt/QtWidgets/QLineEdit:1,
                 from ./codelineedit.h:28,
                 from generated/ui_coloredit.h:19,
                 from coloredit.cpp:22:
/usr/include/qt/QtWidgets/qlineedit.h:122:10: note: candidate: ‘void QLineEdit::setValidator(const QValidator*)’
     void setValidator(const QValidator *);
          ^~~~~~~~~~~~
/usr/include/qt/QtWidgets/qlineedit.h:122:10: note:   no known conversion for argument 1 from ‘QRegExpValidator*’ to ‘const QValidator*’
make[1]: *** [Makefile:2589: generated/coloredit.o] Error 1
```

I'll be happy to provide any other information.

**Comment by Jmgr** [comment]
Hi, thanks for the report. I never tried to compile Actiona with Qt 5.11. I will fix this asap.
